In [ ]:
# 1.1.1 벡터와 행령

import numpy as np

x = np.array([1,2,3])
# x.__class__  # 클래스 이름 표시 하기위해서
x.shape # 다차원 배열의 형상 나타나기위해  1차원에 원소 3개 임을 나타냄.
x.ndim  # 차원수를 나타냄. 

1

In [ ]:
W = np.array([[1,2,3], [4,5,6]])
W.shape # 2행 3열
W.ndim  # 2차원

2

In [ ]:
# 1.1.2 행렬의 원소별 연산

w = np.array([[1,2,3,], [4,5,6]])
x = np.array([[0,1,2,], [4,5,6]])

w+x

array([[ 1,  3,  5],
       [ 8, 10, 12]])

In [ ]:
# 1.1.3 브로트캐스트

A = np.array([[1,2], [3,4]])
A * 10  # 여기서 10을 2x2 행렬로 만든다.

array([[10, 20],
       [30, 40]])

In [ ]:
#1.1.3 브로드캐스트2

A = np.array([[1,2], [3,4]])
b = np.array([10,20])  # 여기서도 [10,20] [10,20] 으로 2x2 행령로 만든다. 

A * b


array([[10, 40],
       [30, 80]])

In [ ]:
# 벡터의 내적

a = np.array([1,2,3])
b = np.array([4,5,6])

np.dot(a,b)

32

In [ ]:
# 행령의 곱

a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

In [ ]:
w1 = np.random.randn(2,4) # 랜덤으로 2행 4열의 숫자 아무거나 뿌려준다.
b1 = np.random.randn(4)   # 랜덤으로 1차원 즉 1행으로 4개 랜덤으로 뿌려준다. 
x = np.random.randn(10,2)  # 랜덤으로 10행 2열 수를 아무거나 뿌려준다.
h = np.matmul(x,w1) + b1  # 특히 행령곱할때 행렬의 형상 중요하다.  b1은 (10,4)로 만들어준다. 브로드캐스트이다.
h

array([[ 1.23557068, -0.11354381,  0.56392806, -0.87781184],
       [-1.98550559, -3.28781015,  0.42905393,  2.77440633],
       [ 2.21271102,  2.67125857, -1.41666588, -0.48263394],
       [ 0.49443659,  2.93359614, -3.65856248,  3.07911384],
       [-0.26401665,  0.48964379, -1.80788792,  2.53938879],
       [ 0.65518423, -0.01015459, -0.20972195,  0.33744287],
       [-2.33621889, -1.50109423, -1.95163329,  4.93132178],
       [ 2.29945248,  1.6588137 , -0.19479297, -1.48681815],
       [ 1.4403037 ,  1.13586285, -0.58995371, -0.24559646],
       [ 2.44214826,  2.74115012, -1.23372912, -0.87166203]])

In [ ]:
b1

array([ 0.97327805,  1.28298682, -1.28342904,  0.78503901])

In [ ]:
h

array([[ 1.23557068, -0.11354381,  0.56392806, -0.87781184],
       [-1.98550559, -3.28781015,  0.42905393,  2.77440633],
       [ 2.21271102,  2.67125857, -1.41666588, -0.48263394],
       [ 0.49443659,  2.93359614, -3.65856248,  3.07911384],
       [-0.26401665,  0.48964379, -1.80788792,  2.53938879],
       [ 0.65518423, -0.01015459, -0.20972195,  0.33744287],
       [-2.33621889, -1.50109423, -1.95163329,  4.93132178],
       [ 2.29945248,  1.6588137 , -0.19479297, -1.48681815],
       [ 1.4403037 ,  1.13586285, -0.58995371, -0.24559646],
       [ 2.44214826,  2.74115012, -1.23372912, -0.87166203]])

In [ ]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [ ]:
a = sigmoid(h)

In [ ]:
a

array([[0.77479209, 0.47164451, 0.63736093, 0.29363142],
       [0.12073316, 0.03599175, 0.60564773, 0.94127702],
       [0.90138517, 0.93530922, 0.1951848 , 0.38163035],
       [0.62115102, 0.94948244, 0.02512214, 0.95602294],
       [0.43437658, 0.62002252, 0.14089358, 0.9268574 ],
       [0.65817777, 0.49746137, 0.44776084, 0.58356923],
       [0.08816742, 0.18226238, 0.12437537, 0.99283475],
       [0.90883168, 0.84007869, 0.45145516, 0.18439979],
       [0.80850168, 0.75691924, 0.35664548, 0.43890766],
       [0.91998537, 0.93941159, 0.22552941, 0.29490859]])

In [ ]:
def sigmoid(x):
    return 1/(1+np.exp(-x))